version: "3.9"
services:
  db:
    image: "postgres:14"
    ports:
      - "54320:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma
